packages:
  - apps/backend
  - apps/backend/apps/*/*
  - apps/backend/packages/*
  - apps/dashboard
  - apps/mobile

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
